[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dispense_program = "CTiZ5kBwGde4oABggEebJvNzDm6XktQ5E4hqfiiuyGvK"
program2 = "5vnYUhFG55QwGuSaCSP2FcoKVXoW3Zyw6u7ciNCgxNPr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
