[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dispensor_program = "6Z4fE5PwpWZx82jx69L3Efutimsa4FnwcC4wwGD9y7N5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
